
var alerts = [
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 6,
    "DeptName": "РСЦ ст. Слюдянка",
    "OrgUnitId": 21,
    "OrgUnitName": "РСП ст. Иркутск",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1446818598000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 6,
    "DeptName": "РСЦ ст. Слюдянка",
    "OrgUnitId": 22,
    "OrgUnitName": "РСП 1 ст. Слюдянка",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1441413031000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 6,
    "DeptName": "РСЦ ст. Слюдянка",
    "OrgUnitId": 22,
    "OrgUnitName": "РСП 1 ст. Слюдянка",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1440808244000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 6,
    "DeptName": "РСЦ ст. Слюдянка",
    "OrgUnitId": 22,
    "OrgUnitName": "РСП 1 ст. Слюдянка",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1442373266000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 6,
    "DeptName": "РСЦ ст. Слюдянка",
    "OrgUnitId": 22,
    "OrgUnitName": "РСП 1 ст. Слюдянка",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1442622654000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 6,
    "DeptName": "РСЦ ст. Слюдянка",
    "OrgUnitId": 633,
    "OrgUnitName": "РСП 2 ст. Слюдянка",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1452817818000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 7,
    "DeptName": "РСЦ ст. Нижний Новгород",
    "OrgUnitId": 27,
    "OrgUnitName": "РСП ст. Нижний Новгород",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1449811841000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 7,
    "DeptName": "РСЦ ст. Нижний Новгород",
    "OrgUnitId": 27,
    "OrgUnitName": "РСП ст. Нижний Новгород",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1455952974000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 7,
    "DeptName": "РСЦ ст. Нижний Новгород",
    "OrgUnitId": 27,
    "OrgUnitName": "РСП ст. Нижний Новгород",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1455953034000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 7,
    "DeptName": "РСЦ ст. Нижний Новгород",
    "OrgUnitId": 27,
    "OrgUnitName": "РСП ст. Нижний Новгород",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1455953094000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 7,
    "DeptName": "РСЦ ст. Нижний Новгород",
    "OrgUnitId": 27,
    "OrgUnitName": "РСП ст. Нижний Новгород",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1455953154000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 35,
    "OrgUnitName": "РСП ст. Завитая",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1442532647000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 35,
    "OrgUnitName": "РСП ст. Завитая",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1442908816000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 35,
    "OrgUnitName": "РСП ст. Завитая",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1443168037000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 35,
    "OrgUnitName": "РСП ст. Завитая",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1441323009000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 35,
    "OrgUnitName": "РСП ст. Завитая",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1441935643000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 35,
    "OrgUnitName": "РСП ст. Завитая",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1443137429000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1442995820000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1443254987000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1442532647000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1442532647000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1441582247000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1440718233000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1441236638000
  },
  {
    "BranchId": 2,
    "BranchName": "Восточно-Сибирский филиал",
    "DeptId": 9,
    "DeptName": "РСЦ ст. Чита",
    "OrgUnitId": 37,
    "OrgUnitName": "РСП ст. Чита",
    "AlertId": 32,
    "AlertName": "Плановый ремонт не окончен в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1442532647000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 38,
    "OrgUnitName": "РСП ст. Рубцовск",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1447986614000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 38,
    "OrgUnitName": "РСП ст. Рубцовск",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1447295434000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 39,
    "OrgUnitName": "РСП ст. Топки",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1453093528000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 39,
    "OrgUnitName": "РСП ст. Топки",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1447551053000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1447295433000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1455762648000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1447381824000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1447295433000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1447295433000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1446604251000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1455503403000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1449601994000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1449887416000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1450492245000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1447038837000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1447295433000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1453080927000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1453343426000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1452750015000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1455503403000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1452997825000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1446699181000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1446949834000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1452748395000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 40,
    "OrgUnitName": "РСП ст. Черепаново",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1452748575000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 41,
    "OrgUnitName": "РСП ст. Чулым",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1446700742000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 41,
    "OrgUnitName": "РСП ст. Чулым",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1446700802000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 41,
    "OrgUnitName": "РСП ст. Чулым",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1450578657000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 10,
    "DeptName": "РСЦ ст. Новосибирск Главный",
    "OrgUnitId": 41,
    "OrgUnitName": "РСП ст. Чулым",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1449140002000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 11,
    "DeptName": "РСЦ ст. Базаиха",
    "OrgUnitId": 42,
    "OrgUnitName": "РСП ст. Базаиха",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1454635841000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 11,
    "DeptName": "РСЦ ст. Базаиха",
    "OrgUnitId": 43,
    "OrgUnitName": "РСП ст. Иланская",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1443835832000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 11,
    "DeptName": "РСЦ ст. Базаиха",
    "OrgUnitId": 43,
    "OrgUnitName": "РСП ст. Иланская",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1455952913000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 11,
    "DeptName": "РСЦ ст. Базаиха",
    "OrgUnitId": 44,
    "OrgUnitName": "РСП ст. Чернореченская",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1435822916000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 11,
    "DeptName": "РСЦ ст. Базаиха",
    "OrgUnitId": 44,
    "OrgUnitName": "РСП ст. Чернореченская",
    "AlertId": 30,
    "AlertName": "Плановый ремонт не начат в срок",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1436837421000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 54,
    "OrgUnitName": "РСП ст. Предпортовая",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1450268841000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 54,
    "OrgUnitName": "РСП ст. Предпортовая",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1450528069000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1450503046000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1443850235000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1450167427000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1450426648000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1443850235000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1444312437000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1446040165000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1446299349000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1450102429000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1449811841000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1455773449000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1454563823000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1446700382000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1449648258000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1446036444000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1443185378000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1443180338000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1443180458000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 14,
    "DeptName": "РСЦ ст. Тосно",
    "OrgUnitId": 55,
    "OrgUnitName": "РСП ст. Тосно",
    "AlertId": 28,
    "AlertName": "Инцидент отклонен Руководителем РСП",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1443180518000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 16,
    "DeptName": "РСЦ ст. Екатеринбург",
    "OrgUnitId": 59,
    "OrgUnitName": "РСП ст. Ишим",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1446192890000
  },
  {
    "BranchId": 3,
    "BranchName": "Западно-Сибирский филиал",
    "DeptId": 16,
    "DeptName": "РСЦ ст. Екатеринбург",
    "OrgUnitId": 60,
    "OrgUnitName": "РСП ст. Кунгур",
    "AlertId": 33,
    "AlertName": "Плановый ремонт не запланирован более трех суток",
    "EntityTypeId": 254,
    "EntityTypeName": "Плановый ремонт",
    "CreatedTime": 1452828619000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 17,
    "DeptName": "РСЦ ст. Ярославль",
    "OrgUnitId": 64,
    "OrgUnitName": "РСП ст. Ярославль",
    "AlertId": 21,
    "AlertName": "Нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1450295185000
  },
  {
    "BranchId": 4,
    "BranchName": "Забайкальский филиал",
    "DeptId": 17,
    "DeptName": "РСЦ ст. Ярославль",
    "OrgUnitId": 64,
    "OrgUnitName": "РСП ст. Ярославль",
    "AlertId": 22,
    "AlertName": "Более 3 суток нет подтверждения выполнения работ по Обращению",
    "EntityTypeId": 314,
    "EntityTypeName": "Обращение",
    "CreatedTime": 1450589458000
  },
  {
    "BranchId": 5,
    "BranchName": "Юго-Восточный филиал",
    "DeptId": 19,
    "DeptName": "РСЦ ст. Кочетовка",
    "OrgUnitId": 194,
    "OrgUnitName": "РСП 2 ст. Кочетовка",
    "AlertId": 12,
    "AlertName": "Работы по Инциденту не согласованы более 3 дней",
    "EntityTypeId": 313,
    "EntityTypeName": "Инцидент",
    "CreatedTime": 1449725423000
  }
];


/*
var arr = s.split('\n').map((strRow) => strRow.split('\t')).filter((arrRow) => arrRow.length > 2)
    .map(function(arrRow){ return {
        BranchId: Number(arrRow[0]),
        BranchName: arrRow[1],
        DeptId: Number(arrRow[2]),
        DeptName: arrRow[3],
        OrgUnitId: Number(arrRow[4]),
        OrgUnitName: arrRow[5],
        AlertId: Number(arrRow[6]),
        AlertName: arrRow[7],
        EntityTypeId: Number(arrRow[8]),
        EntityTypeName: arrRow[9],
        CreatedTime: + moment(arrRow[10])
    }})
*/

